<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Paypalcz.cz -  Váš intergrátor playtební brány')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.css'))
        //->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
        ?>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.js'))
        //->prependFile($this->basePath('js/jquery-3.3.1.js'))
        ?>    

    </head>
    <body>
        <?php
        /*
          <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
          <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?= $this->url('home') ?>">
          <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
          </a>
          </div>
          <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
          </ul>
          </div>
          </div>
          </nav>

         */


        /*
         * 
         * 
          O systému PayPal
          Jak systém funguje
          Jak založit účet
          Integrace do webu
          Poplatky za platby
         * 
         */
        ?>

        <nav class="navbar navbar-expand-md bg-primary navbar-dark mb-4 col-8 offset-2">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">O systému PayPal</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('home') ?>">  Jak systém funguje </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('home') ?>">  Jak založit účet </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('home') ?>">  Integrace do webu </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('home') ?>">  Poplatky za platby </a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="hledat" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Hledat</button>
                </form>
            </div>
        </nav>        



        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
