<div class="row col-md-10">

    <div class="col-md-8">
        <h1>O systému PayPal</h1>
        <div>
            <span>
                Podpora pro ČR je konečně v Praze, nejkrásnějším městě zvaném srdce Evropy. 
                Je konec všem dohadům jak si založit účet u PayPal a jak integrovat tento vynikající platební systém do vašich webových stránek. 
                Jsme tady pro Vás a rádi Vám pomůžeme.
            </span>            

            <li> Víte, že integrací platebního systému PayPal získáte nejlepší platební podmínky? </li>
            <li> Věděli jste, že systém plateb platebními kartami zvyšuje obrat internetových  obchodů, aukcí a dalších až o 14%? </li>
            </br>
        </div>


    </div>

    <div class="col-md-4">
        <div class="box" style="">
            <h3>Potřebujete poradit?</h3>
            <p>Technická podpora k implementacím PayPal:</p>
            <h3><a href="mailto:podpora@paypalcz.cz">podpora@paypalcz.cz</a></h3>
            <p>Ostatní podporu vyřizuje pouze:</p><p>
            </p><h3><a href="http://www.paypal.com/cz">https://www.paypal.com/cz</a></h3>
        </div>        
    </div>

</div>

<h3 class="row top col-md-6 pt-4 pb-4">Postup pro založení PayPal účtu</h3>
<div class="row pt-2 pb-2 col-md-10 bg-primary text-white">

    <div class="col-md-4">
        <div class="row">
            <div class="col-md-2"><h2 class="text-center bg-white text-dark bt-3">1</h2></div>
            <div class="col-md-8">Klikněte na <i>Založit účet</i> a vyberte Business Account.</div>    
        </div>

    </div>

    <div class="col-md-4">
        <div class="row">
            <div class="col-md-2"><h2 class="text-center bg-white text-dark bt-3">2</h2></div>
            <div class="col-md-8">Zadejte pravdivě vaše informace a potvrďte je.</div>    
        </div>
    </div>

    <div class="col-md-4">
        <div class="row">
            <div class="col-md-2"><h2 class="text-center bg-white text-dark bt-3">3</h2></div>
            <div class="col-md-8">Integrujte PayPal do vašeho webu nebo obchodu.</div>    
        </div>
    </div>    
</div>

<div class="row pt-5">
    <span>
        Pro lepší pochopení postupu doporučujeme prostudovat stránky "jak založit účet":/jak-zalozit-ucet .</br>
        Založení účtu u PayPal  během několika sekund: 
    </span>

</div>

<div class="row col-lg-5 pt-3">
    <a target="_new" href="https://www.paypal.com/cz/mrb/pal=XJWY459HEHR5A" 
       class="btn-success col-lg-5 p-2 bg-primary text-center font-weight-bold ">Založit účet</a>
</div>



