
<h1 class="row col-md-10">Integrace do webu</h1>
<div class="row col-md-11">
    <div class="col-md-8">
        <p class="mb-2" >
            Je nutné správně napojit platební systém PayPal na Vaše webové stránky 
            nebo internetový obchod na kterých prodáváte zboží a nebo služby. Tomuto napojení říkáme intergace.	
        </p>
        <p class="mb-2" >

            Věříme, že mnozí z Vás jsou velmi šikovní a zvládli by to sami, 
            ale pokud chcete mít naprostou jistotu, že je integrace provedena správně, 
            pak je rozumnější si integraci objednat.	
        </p>
        <p class="mb-2" >
            Také doporučujeme, aby jste se pečlivě seznámili s jednotlivými typy účtů, 
            protože u některých není možné přijímat platby z platebních karet. 
            Aby bylo správně pochopeno, bez správného účtu nelze intergaci provést. Tak a teď k možným typům integrace.
        </p>
    </div>

    <div class="col-md-4">
        <div class="box" style="">
            <h3>Potřebujete poradit?</h3>
            <p>Technická podpora k implementacím PayPal:</p>
            <h3><a href="mailto:podpora@paypalcz.cz">podpora@paypalcz.cz</a></h3>
            <p>Ostatní podporu vyřizuje pouze:</p><p>
            </p><h4><a href="http://www.paypal.com/cz">https://www.paypal.com/cz</a></h4>
        </div>        
    </div>
</div>

<div class="row col-md-12 mt-4">

    <h4 class="row col-md-10">Možnost č.1</h4>

    <div class="col-md-8">
        <p>
            <strong>Integrace možnosti zaplacení jednotlivé položky či košíku kreditní kartou či účtem PayPal</strong> <br/><br/>

            Stisknutím tlačítka <i>Zaplatit</i> (<i>Zaplatit kreditní kartou</i>,<i>Zaplatit PayPalem</i>) je zákazník přeměrován na stránky PayPalu, 
            kde vyplní údaje o kreditní kartě nebo se přihlásí ke svému PayPal účtu. Zákazník při placení (a na na výsledné faktuře od PayPalu) 
            vidí buďto souhrnný údaj o objednávce (číslo,název), nebo kompletní výpis položek. <br/><br/>

            Po úhradě je zákazník nasměrován zpět na stránky obchodníka a sytém internetového obchodu zpracuje informace o proběhlé (popř. zamítnuté) platbě.
        </p>    

    </div>

    <div class="col-md-4">
        <div class="row">
            <a href="https://www.paypal.com/cz/mrb/pal=XJWY459HEHR5A" class=" row btn-success col-md-5 p-1 btn-block bg-primary text-center font-weight-bold"> Ukázka implementace</a>
        </div>
        <div class="row">
            <a href="http://localhost/ukazka-obchod">

                <div class="row "><strong>Orientační cena:</strong></div>
                <div class="row h4 udaj">1100,-/hod. <span class="ml-3 text-muted">+ DPH</span></div>
                <div class="row ">Odhad náročnosti: 3-6 hod.</div>
                <div class="row ">Předběžná orientační cena. Cena se liší dle náročnosti implementace. <i>Především dle požadavků na zpracování platby.</i> Změna ceny vyhrazena.</div>

            </a>
        </div>

        <div class="row mt-3">
            <a href="http://localhost/objednavka-implementace?implementace=1" class="row btn-success btn-block col-md-5 p-1 bg-primary text-center font-weight-bold"> Objednat</a>
        </div>

    </div>
</div>

<div class="row col-md-12 mt-4">

    <h4 class="row col-md-10">Možnost č.2</h4>

    <div class="col-md-8">
        <p>
            <strong>Použití nákupního košíku PayPal pro vytvoření jednoduchého internetového obchodu</strong> <br/><br/>

            Tato možnost spočívá v propojení současných internetových stránek obchodníka s nákupním košíkem 
            PayPalu pomocí tlačítek <i>Přidat do košíku</i>, <i>Zobrazit košík</i> a <i>Zaplatit</i> (kreditní kartou či PayPalem). 
            Webové stránky zobrazující produkty obchodníka se tak změní na jednoduchý internetový obchod.

            Samotná platba probíhá takřka stejně jako v možnosti č. 1, 
            zákazník jen provede potvrzení košíku na stránkách PayPalu. 
            Ty se dají upravit do podoby ladící s již existujícím webem zákazníka.                    

        </p>    
    </div>

    <div class="col-md-4">
        <div class="row">
            <a href="https://www.paypal.com/cz/mrb/pal=XJWY459HEHR5A" class="row btn-success col-md-5 btn-block p-1  bg-primary text-center font-weight-bold"> Ukázka implementace</a>
        </div>            

        <div class="row" ><a href="http://localhost/ukazka-kosik">
                <div class="row "><strong>Orientační cena:</strong></div>
                <div class="row h4 udaj">1100,-/hod. <span class="ml-3 text-muted">+ DPH</span></div>
                <div class="row">Odhad náročnosti: 6-8 hod.</div>
                <div class="row">Předběžná orientační cena. Cena se liší dle náročnosti implementace. Změna ceny vyhrazena.</div>
            </a>
        </div>

        <div class="row">
            <a href="http://localhost/objednavka-implementace?implementace=1" class="row btn-success btn-block col-md-5 p-1 bg-primary text-center font-weight-bold"> Objednat</a>
        </div>

    </div>
</div>

<div class="row col-md-12 mt-4">

    <h4 class="row col-md-10">Možnost č.3</h4>

    <div class="col-md-8">
        <p>
            <strong>Integrace možnosti vyřízení platby pomocí PayPal Express Checkout</strong> <br/><br/>


            Tato možnost spočívá v tom, že v již existujícím internetovém obchodu
            nejsou po zákazníkovi vyžadovány žádné osobní údaje, 
            pro účely platby software obchodu obdrží ty informace, 
            které uživatel zadal při své registraci PayPal účtu. 
            Tato možnost integrace dokáže zpracovat objednávku ihned, 
            bez nutnosti registrace uživatele v internetovém obchodu obchodníka. 
            Dle studie PayPalu možnost Express Checkout zvyšuje pravděpodobnost uskutečnění platby o 14%, 
            právě protože eliminuje bariéry (vyplňování registračního formuláře) pro uskutečnění platby. 
            Express Checkout tak snižuje množství tzv. mrtvých (opuštěných) košíků.
        </p>
        <p>
            Zákazník je po kliknutí na tlačítko <i>Checkout with PayPal</i> přesměrován na PayPal, kde potvrdí jen <i>způsob</i> platby. 
            Následně je přesměrován na stránky obchodníka, kde porvrdí obejdnávku. 
            Ve stejném okamžiku PayPal provede platbu - inkasuje kreditní kartu nebo PayPal účet.

        </p>
    </div>

    <div class="col-md-4">
        <div class="row">
            <a href="https://www.paypal.com/cz/mrb/pal=XJWY459HEHR5A" class="row btn-success col-md-7 btn-block p-1  bg-primary text-center font-weight-bold"> Ukázka implementace</a>
        </div>

        <div class="row">
            <a href="http://localhost/ukazka-checkout">
                <div class="row "><strong>Orientační cena:</strong></div>
                <div class="row h4 udaj">1100,-/hod. <span class="ml-3 text-muted">+ DPH</span></div>
                <div class="row">Odhad náročnosti: 8-10 hod.</div>
                <div class="row">Předběžná orientační cena. Cena se liší dle náročnosti implementace. Změna ceny vyhrazena.</div>
            </a>
        </div>

        <div class="row">
            <a href="http://localhost/objednavka-implementace?implementace=1" class="row btn-success btn-block col-md-5 p-1 bg-primary text-center font-weight-bold"> Objednat</a>
        </div>

    </div>
</div>



<div class="row col-md-12 mt-4">

    <div class="col-md-8">
        <h4 class=mt-4">Možnost č.4 - Online terminál pro kamenné obchody</h4>
        <p>
            Integrace spočívá v zapojení platebního terminálu na míru, 
            který lze použít pro placení transakcí pomocí platebních či kreditních karet zákazníků. 
        </p>

    </div>

    <div class="col-md-4">
        <div class="row"><a href="http://localhost/ukazka-checkout">
                
                    <div class="row "><strong>Orientační cena:</strong></div>
                    <div class="row h4 udaj">700,- <span class="ml-3 text-muted">+ DPH</span></div>
                    <div class="row">Změna ceny vyhrazena.</div>
                
            </a>
        </div>

        <div class="row">
            <a href="http://localhost/objednavka-implementace?implementace=1" class="row btn-success btn-block col-md-5 p-1 bg-primary text-center font-weight-bold"> Objednat</a>
        </div>

    </div>
</div>
