<div class="row col-md-10">

    <div class="col-md-8">
        <h1>Jak založit účet</h1>
        <span class="row mb-2" >
            Krok č.1
            ========

            Chcete-li založit účet, klikněte na tlačítko *Založit účet*

            Doporučujeme, aby jste se nejdříve seznámili s celým procesem založení účtu a teprve potom zahájili ostré založení účtu. 

            Celý proces je srozumitelně popsán a důležité části jsou přeloženy do českého jazyka. Můžete se podívat na "stránku s překlady klíčových formulářů":/preklad .
        </span>


    </div>

    <div class="col-md-4">
        <div class="box" style="">
            <h3>Potřebujete poradit?</h3>
            <p>Technická podpora k implementacím PayPal:</p>
            <h3><a href="mailto:podpo%72%61%40paypalc%7a.cz">podpora@paypalcz.cz</a></h3>
            <p>Ostatní podporu vyřizuje pouze:</p><p>
            </p><h3><a href="http://www.paypal.com/cz">https://www.paypal.com/cz</a></h3>
        </div>        
    </div>

</div>





<div class="row col-md-10">



    <div class="zalozit-container">
        <a target="_new" href="https://www.paypal.com/cz/mrb/pal=XJWY459HEHR5A" class="zalozit">Založit účet</a>
    </div>




    Krok č.2 - budete přesměrování na stránky PayPal
    ================================================

    Klikněte na tlačítko označené žlutou šipkou.

    <img src="./PayPal CZ - Jak založit účet_files/krok2.jpg">

    Krok č.3 - zde věnujte pozornost správnému výběru typu účtu
    ===========================================================

    *Personal account* je ideální pro online nakupování. Při použití vaší kreditní karty neuvádíte expoziční dobu. Rychlé ověření vaší platby bez zadání  čísla vaší kreditní karty a vaší adresy. Plus,můžete zdarma zasílat peníze rodině a přátelům. U tohoto typu účtu nemáte možnost přijímat platby kreditními kartami z webu. "**Nápověda k založení Osobního účtu**":/zalozeni-osobniho-uctu .

    <img src="./PayPal CZ - Jak založit účet_files/krok3.jpg">

    *Premier account* je perfektní pro nakupování a prodej na eBay nebo obchodních webech. Umožňuje přijímat všechny typy platebních možností. Obchodujete jako fyzická osoba pod vlastním jménem, tedy jako podnikatel OSVČ. "**Nápověda k založení Premier účtu**":/zalozeni-premier-uctu .

    <img src="./PayPal CZ - Jak založit účet_files/krok3b.jpg">

    *Business account* je pravá volba pro vaše online obchodování. Umožňuje přijímat všechny typy platebních možností. Obchodujete pod jménem firmy nebo skupiny, tedy jako právnická osoba. "**Nápověda k založení Business účtu**":/zalozeni-business-uctu .

    <img src="./PayPal CZ - Jak založit účet_files/krok3c.jpg">


</div>
