<div class="row col-md-10">

    <div class="col-md-8">
        <h1>Jak systém funguje</h1>
        <span class="row mb-2" >
            Systém PayPal je elektronický platební prostředek. 
            Účet v systému si lze představit jako běžný bankovní účet, 
            který se dá ovšem přímo napojit na miliony internetových obchodů po celém světě 
            a přesun peněz z účtu na účet probíhá okamžitě. Dá se říci, že na internetu mají všichni stejnou banku - PayPal.
        </span>
        
        <span  class="row mb-2">
            Systém je ideální pro nákup a prodej zboží za malé a střední částky, nejčastěji bývá spojován s internetovou aukční síní eBay, kde funguje jako hlavní platební protředek pro desetitisíce transakcí denně.
        </span>
        </br>
        <span  class="row mb-2">
            Na PayPalový účet lze přesunout peníze nejlépe platební kartou. Tím pádem *PayPal může fungovat jako brána pro příjem platebních karet* - částku, která se strhne zákazníkovi z účtu, obchodník okamžitě vidí na svém PayPal účtu. PayPal přijímá všechny hojně používané druhy platebních karet. Následně je možné si peníze nechat poslat na bankovní účet běžným bankovním převodem.
        </span>
        <span  class="row mb-2">
        Výhodou použití PayPalu pro prodej na internetu je instantní funkčnost - obchodník může během hodin zprovoznit přijímání platebních karet. A přitom je možné kompletně vynechat jednání s bankami či jinými bránami pro jejich přijímání.
        </span>

    </div>

    <div class="col-md-4">
        <div class="box" style="">
            <h3>Potřebujete poradit?</h3>
            <p>Technická podpora k implementacím PayPal:</p>
            <h3><a href="mailto:podpo%72%61%40paypalc%7a.cz">podpora@paypalcz.cz</a></h3>
            <p>Ostatní podporu vyřizuje pouze:</p><p>
            </p><h3><a href="http://www.paypal.com/cz">https://www.paypal.com/cz</a></h3>
        </div>        
    </div>

</div>

