
<h1 class="row mb-4">Poplatky a platby</h1>
    <h5 class="mt-4 mb-4">Inkasování plateb z ČR</h5>

<div class="row col-md-6">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Měsíční prodej přes PayPal
                </th>
                <th>
                    Cena v Kč
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    0 - 70.000,-
                </td>
                <td>
                    3,4% + 10,-
                </td>
            </tr>
            <tr>
                <td>
                    70.001,- - 280.000,-
                </td>
                <td>
                    2,9% + 10,-
                </td>
            </tr>
            <tr>
                <td>
                    280.001,- - 1.500.000,-
                </td>
                <td>
                    3,7% + 10,-
                </td>
            </tr>
            <tr>
                <td>
                    1.500.000,- 3.000.000,-
                </td>
                <td>
                    2,4% + 10,-
                </td>
            </tr>
            <tr>
                <td>
                    &gt; 3.000.000,-
                </td>
                <td>
                    1,9% + 10,-
                </td>
            </tr>
        </tbody>

    </table>    
</div>

<h5 class="mt-4 mb-4">Převod na bankovní účet</h5>


<div class="row col-md-6">

    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Částka
                </th>
                <th>
                    Cena v Kč
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                  Převod na bankovní účet, více než 3000,-  
                </td>
                <td>
                    zdarma
                </td>
            </tr>
            <tr>
                <td>
                  Převod na bankovní účet, méně než 3000,-  
                </td>
                <td>
                    30,-
                </td>
            </tr>
            <tr>
                <td>
                  Neúspěšný převod na bankovní účet (např. špatné číslo účtu) 
                </td>
                <td>
                    200,-
                </td>
            </tr>
        </tbody>
    </table>
</div>    