
<h1 class="row col-md-10">Jak založit účet</h1>
<div class="row col-md-10">

    <div class="col-md-8">
        <h4 class="col-md-8">Krok č.1</h4>
        <div class="mb-2" >

            Chcete-li založit účet, klikněte na tlačítko <b>&nbsp;založit účet</b>
            Doporučujeme, aby jste se nejdříve seznámili s celým procesem založení účtu a teprve potom zahájili ostré založení účtu. <br/>
            Celý proces je srozumitelně popsán a důležité části jsou přeloženy do českého jazyka. 
            Můžete se podívat na "stránku s překlady klíčových formulářů":/preklad .
        </div>
        <div class="row col-md-12 p-1 m-3">
            <a target="_new" href="https://www.paypal.com/cz/mrb/pal=XJWY459HEHR5A" 
               class="btn-success col-md-3 p-2 bg-primary text-center font-weight-bold ">Založit účet</a>
        </div>        
    </div>

    <div class="col-md-4">
        <div class="box" style="">
            <h3>Potřebujete poradit?</h3>
            <p>Technická podpora k implementacím PayPal:</p>
            <h3><a href="mailto:podpora@paypalcz.cz">podpora@paypalcz.cz</a></h3>
            <p>Ostatní podporu vyřizuje pouze:</p><p>
            </p><h4><a href="http://www.paypal.com/cz">https://www.paypal.com/cz</a></h4>
        </div>        
    </div>
</div>

<div class="row col-md-12 mt-4">


    <h4 class="col-md-12">Krok č.2 - budete přesměrování na stránky PayPal</h4>
    <div class="col-md-12 " >
        Klikněte na tlačítko označené žlutou šipkou. <br/>
        <img src="<?= $this->basePath() . '/img/jak_zalozit_ucet/jak_zalozit_ucet_sign_up.jpg' ?>">
    </div>
</div>

<div class="row col-md-12 mt-5">

    <h4 class="col-md-12">Krok č.3 - zde věnujte pozornost správnému výběru typu účtu</h4>
    <p class="col-md-12 mb-2" >
        <strong>Personal account</strong> je ideální pro online nakupování. 
        Při použití vaší kreditní karty neuvádíte expoziční dobu. 
        Rychlé ověření vaší platby bez zadání  čísla vaší kreditní karty a vaší adresy. 
        Plus,můžete zdarma zasílat peníze rodině a přátelům. U tohoto typu účtu nemáte možnost přijímat platby kreditními kartami z webu. 
        <strong>Nápověda k založení Osobního účtu</strong>:/zalozeni-osobniho-uctu .

    </p>

    <p class="col-md-12 mb-2" >
        <strong>Business account</strong> je pravá volba pro vaše online obchodování. 
        Umožňuje přijímat všechny typy platebních možností. 
        Obchodujete pod jménem firmy nebo skupiny, tedy jako právnická osoba. 
        <strong>Nápověda k založení Business účtu</strong>:/zalozeni-business-uctu .
    </p>
    
    <p class="col-md-12 mb-2">
        <img src="<?= $this->basePath() . '/img/jak_zalozit_ucet/jak_zalozit_ucet_personal_or_business.jpg' ?>">
    </p>

</div>
